#ifndef MONAD_SPLIT_LINE_NUMBER
#define MONAD_SPLIT_LINE_NUMBER -1
#endif
#define MONAD_SPLIT (MONAD_SPLIT_LINE_NUMBER == __LINE__ || MONAD_SPLIT_LINE_NUMBER == -1)
#define NO_MP_PART -1
#define MP_PART_NUMBER NO_MP_PART
#define MP_PART(x) (MP_PART_NUMBER == (x) || MP_PART_NUMBER == NO_MP_PART)
